package resourcetype

// zpa Types
const (
	ZPAAppConnectorGroup               = "zpa_app_connector_group"
	ZPAServiceEdgeGroup                = "zpa_service_edge_group"
	ZPAProvisioningKey                 = "zpa_provisioning_key"
	ZPAApplicationServer               = "zpa_application_server"
	ZPABACertificate                   = "zpa_ba_certificate"
	ZPAServerGroup                     = "zpa_server_group"
	ZPASegmentGroup                    = "zpa_segment_group"
	ZPAApplicationSegment              = "zpa_application_segment"
	ZPAApplicationSegmentPRA           = "zpa_application_segment_pra"
	ZPAApplicationSegmentInspection    = "zpa_application_segment_inspection"
	ZPAApplicationSegmentBrowserAccess = "zpa_application_segment_browser_access"
	ZPACBIBannerController             = "zpa_cloud_browser_isolation_banner"
	ZPACBICertificate                  = "zpa_cloud_browser_isolation_certificate"
	ZPACBIExternalIsolationProfile     = "zpa_cloud_browser_isolation_external_profile"
	ZPAPolicyType                      = "zpa_policy_type"
	ZPAPolicyAccessRule                = "zpa_policy_access_rule"
	ZPAPolicyTimeOutRule               = "zpa_policy_timeout_rule"
	ZPAPolicyForwardingRule            = "zpa_policy_forwarding_rule"
	ZPAPolicyInspectionRule            = "zpa_policy_inspection_rule"
	ZPAPolicyIsolationRule             = "zpa_policy_isolation_rule"
	ZPACustomerVersionProfile          = "zpa_customer_version_profile"
	ZPAEnrollmentCertificate           = "zpa_enrollment_cert"
	ZPALSSController                   = "zpa_lss_config_controller"
	ZPAInspectionCustomControl         = "zpa_inspection_custom_controls"
	ZPAInspectionProfile               = "zpa_inspection_profile"
	ZPAMicrotenant                     = "zpa_microtenant_controller"
)
