ignore:
  - "vendor/**/*"
  - "dist/**/*"

coverage:
  status:
    project:
      default:
        target: 85% #overall project / repo coverage

    patch:
      service:
        target: 60%
        threshold: 30%
        flags:
          - zpaprovider

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: yes       # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post]
  branches:
    - master

flags:
  zpaprovider:
      carryforward: true
      paths:
        - zpa/*.go

github_checks:
  annotations: true